### PR TITLE
Fix issue where files do not get deleted after emptying recycle bin

### PR DESCRIPTION
**Pull request by tomfulton**
Hi!  I noticed that after emptying the Media Recycle Bin, the files from those media items still existed on my blob and were accessible from the web.  When using the default file system provider, the files are deleted from disk when the Recycle Bin is empty.

It looks like it was just a mixup with the path.  `DeleteDirectory` was receiving `\\media\\205276` as the path, and `DirectoryExists` was returning `false` for that and never tries to delete the items.  Running the path through `this.FixPath()` seems to fix the issue.

Does this seem like the correct fix?  I tried placing this in a couple other areas to make it more global but did not have much luck.

This was in Umbraco 7.3.0

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
Yeah, that looks correct to me. Thanks!

**Comment by tomfulton** [comment]
I tried but was getting stuck up with the Storage Emulator, I will give it another shot though.

I think the tests are passing because it's using the "fixed" version of the path - ie `1010/media.jpg` instead of `\\media\\205276` which is what we're getting at runtime.

**Comment by JimBobSquarePants** [comment]
Ah... true that. I don't  I have relative tests set up specifically for relative deleting. (Bad James!)

I recall the emulator being an issue to set up. That would be great if you could.

**Comment by tomfulton** [comment]
New test `TestDeleteDirectoryRelative` added above that addresses this issue.

Also, did some digging in the Umbraco source just to make sure, and confirmed it's the source of the strange path format (`\\media\\1234`), from [this line](https://github.com/umbraco/Umbraco-CMS/blob/d50e49ad37fd5ca7bad2fd6e8fc994f3408ae70c/src/Umbraco.Core/Persistence/Repositories/VersionableRepositoryBase.cs#L572).  I suspect this type of path will only occur for deletes, so hopefully that means this method is a good place for it and we won't run into it elsewhere :smile:

**Pull request merged**
