### PR TITLE
Created configurable public container access type.

### PR DESCRIPTION
**Pull request by tmoxon**
As per feature request #67 I've created a change set to facilitate configurable public access type for containers. I'd be happy to make any further modifications you feel are required to make this viable - assuming you agree that it is.

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
Hi @tmoxon Is this different from #64 ?

**Comment by tmoxon** [comment]
Hi @JimBobSquarePants, ah I managed to miss that...bit of a waste of time...very similar PRs! I'd perhaps argue that this it's worth supporting any of the container types, though I'm not sure if people would ever choose public, and #64 includes the install step so maybe that puts it ahead. I'll not be offended if you drop this...would be great to get one of them in. Thanks

**Comment by tmoxon** [comment]
@JimBobSquarePants - as discussed I'm killing this as #64 does the same thing. It would be really useful for us if #64 could get in soon.

**Comment by JimBobSquarePants** [comment]
Ok coke, I think #64 still needs additional work though, will double check.

**Comment by tmoxon** [comment]
@JimBobSquarePants For info we are now running off a build using #64 which is working well. However there is a side effect that we had to write a custom IImageService for image processor that could access private blobs. I wasn't in a position to do this in a way I can submit to the repo though I might be able to find time to do so if it would help. If I were to look at that it'd be good to get your direction on how that should look. Could the file system provider ship with an IImageService that utilises its own access patterns?

**Comment by JimBobSquarePants** [comment]
No, the FileSystemProvider and ImageProcessor should be kept separate. 

A custom IImageService makes sense so if you ever get the chance to publish one go for it.

**Comment by tmoxon** [comment]
Thanks, yep, understood. Might just be worth mentioning in the documentation for private blob support that ImageProcessor won't be able to read from them (without a custom ImageService).

**Comment by neilha** [comment]
@tmoxon would you be happy to share your custom IImageService? Think I am going to need to do something very similar. Thanks.

**Pull request closed without merging**
