### PR TITLE
Added cdn to replace the blob url when serving files with virtual path disabled 

### PR DESCRIPTION
**Pull request by KennethJakobsen**
Found my old PR, and i need this again so i'm resubmitting.

### CODE REVIEW

**Comment by KennethJakobsen** [comment]
@JimBobSquarePants We would like to use this feature at Codegarden, will you look it over?

**Comment by JimBobSquarePants** [comment]
@Jeavon would you be able to have a look at this please, I have limited testing powers just now

**Comment by Jeavon** [comment]
@KennethJakobsen could you please explain what this is for and the use case?

**Comment by KennethJakobsen** [comment]
@Jeavon When AzureBlobFileSystem.DisableVirtualPathProvider is set to true we would like to enable Azure CDN.
Which is what this pull request is all about.

**Comment by Jeavon** [comment]
@KennethJakobsen so if VPP is disabled, this would let you define a absolute url (CdnUrl) that would get returned as the media url? I don't understand why you would need to do that?

**Comment by KennethJakobsen** [comment]
@Jeavon Because this is the url of my cdn (which is automatically populated).

Blob:
https://cg18storage.blob.core.windows.net/media/1009/slave-and-eagle-white.png

CDN
http://slaveandeagle.azureedge.net/media/1009/slave-and-eagle-white.png

**Comment by JimBobSquarePants** [comment]
You can't run the image cropper against an external URL though?

**Comment by Jeavon** [comment]
Also isn't the CDN is going to cache those image urls and not update when the source image has been updated?

**Comment by idseefeld** [comment]
For images this would be done by ImageProcessor.Web.AzureBlobCache. I am not sure this plugin support's other media files like PDF, Zip etc.
I am pretty sure this pull request is in the wrong place. FileSystemProviders are used for internal usage and should store just relative path in database. This was one of the main issues with the 'ancestor' Azure provider: https://github.com/idseefeld/UmbracoAzureBlobStorage/
Actually URL rewriting should be done for Frontend rendering like it is done by the mentioned ImageProcessor.Web.AzureBlobCache plugin. For Media files other than images you should probably write a HttpModule.
Yours
Dirk

**Comment by idseefeld** [comment]
Hi @KennethJakobsen, JimBobSquarePants & Jeavon are right. CDN-URLs prevent ImageProcessor to render crops and CDN might not deliver the lates version of an uploaded media item. The last depends on how items are updated.
For other media items than images your approach might be usefull. 
But I think the CDN option for the FileSystemProvider would be quite missleading. From my point of view even the _DisableVirtualPathProvider_ should be removed. Maybe it is mostly for backward compatibilty(?)
Images are nicely served with CDN-URLs when you configure ImageProcessor.Web.Plugins.AzureBlobCache correctly.
For other media items you should provide another HttpModule like ImageProcessor.Web.
Yours
Dirk

**Pull request closed without merging**
