### PR TITLE
Added support for CDN

### PR DESCRIPTION
**Pull request by KennethJakobsen**

### CODE REVIEW

**Comment by Jeavon** [comment]
@KennethJakobsen I'm trying to get my head around your PR, could explain what/why it's needed?

**Comment by KennethJakobsen** [comment]
I'm not sure what you mean, but in my situation I need Umbraco to serve the url of the CDN an not the blob storage. Does that answer your question?

**Comment by Jeavon** [comment]
Ok, so you have a CDN attached to your storage account and when you output mediaItem.Url you want it to output the absolute path to your CDN, am I understanding correctly?

**Comment by KennethJakobsen** [comment]
Correct!

Sendt fra Outlook Mobile




On Sun, Apr 24, 2016 at 8:11 AM -0700, "Jeavon" <notifications@github.com> wrote:












Ok, so you have a CDN attached to your storage account and when you output mediaItem.Url you want it to output the absolute path to your CDN, am I understanding correctly?

**Comment by Jeavon** [comment]
Ok, and are you using this for mostly files or images?

**Comment by KennethJakobsen** [comment]
Images but also files

Sendt fra Outlook Mobile




On Sun, Apr 24, 2016 at 11:57 AM -0700, "Jeavon" <notifications@github.com> wrote:












Ok, and are you using this for mostly files or images?

**Comment by sonphnt** [comment]
Hi. do we have any answers for this?

**Comment by idseefeld** [comment]
see https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/pull/105 for latest comments

**Pull request closed without merging**
