### PR TITLE
Package Unification

### PR DESCRIPTION
**Pull request by Jeavon**
Oh yes, this makes the same XDT transforms work for both NuGet and Umbraco packages!
Of course I have changed your .transform files to .xdt files

I'm opening this PR now so that we can discuss it although it's not 100% complete, it is working fully for install actions, uninstall files to follow

Something to discuss is that having correctly installed this package with Umbraco, the package will cause the entire site and Umbraco to YSOD as of course the configuration in the FileSystemProviders.config does not contain valid keys.
The only way around this I can think of is to have a post install control (I'm not sure if this can be a Angular view/controller now or if it must still be a UserControl) where the user can enter the keys into a form and then have it perform the transform with the entered keys.

Any thoughts...?

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
You're a bloody wizard mate! This looks awesome!

I think a control would be a great idea. That would allow us to simply insert the correct parts into the config then which would make it a lot easier for developers to implement. A yellow screen would be pretty rough.

I have no idea how to implement that kind of stuff though with Umbraco and I'm struggling to think of a package that does something similar.

**Comment by Jeavon** [comment]
Cool, glad you like it! I'll work on that control screen and see how it goes. Huge credit due to @TimGeyssens for the XDT idea and original code it makes most packages so much easier to create for both NuGet and Umbraco!

**Comment by Jeavon** [comment]
That was really very tricky but install is now fully working! 

Uninstall and then tidy up, phew! 

image

**Comment by Jeavon** [comment]
That's it, working for both install and uninstall!

To summarise, there are now both install and uninstall xdt files for both web.config and UmbracoFileSystemProviders.config these work perfectly in the NuGet package. 
For Umbraco the same xdt files are used as a data source for the package installer control screen (this is really a ascx but I've used it as a Angular view so it's ready when Umbraco requires a View) to generate the form to allow the user to enter the correct parameters. When the user saves the xdt file is updated and the transform is executed. For uninstall, Umbraco uses it's default package actions to execute the uninstall xdt.

I think this is pretty cool! Happy days!

I could split all of the Umbraco installer stuff into a separate project, the only reason to do this is that we wouldn't need to add the Microsoft.Web.Xdt dependency to the NuGet package (to avoid compiler warnings).

p.s I think I've upgrade the solution file to VS2015, I'm sure I can unpick it if you would prefer to keep it to VS2013

**Comment by JimBobSquarePants** [comment]
This all looks absolutely amazing. I'm so glad you've helped me on this. :smile: 

Just saw the video too and I really like the light as candyfloss bit. I really think I should add you to the collaborating team and give you full access to the repo if you are keen?

How difficult would it be to separate the installer stuff and what are the generated warnings?

**Comment by Jeavon** [comment]
Fantastic and of course! I would love to get it up on Our as a beta perhaps for people to try?

It wouldn't be very difficult to move it out, I had no idea it would end up having so much in it when I started out! There won't be any warnings as I add the dependency to the Microsoft.Web.Xdt nuspec but if you are using the NuGet package you don't really need Microsoft.Web.Xdt...

I'm thinking it probably does make sense to move it to a different project and keep the NuGet package pure?

**Comment by JimBobSquarePants** [comment]
Perfect. That's you added. I'll update the readme in due course

I'm inclined to agree. I'd be a bit weirded out if I saw an extra dependency that wasn't being used in my Nuget package.

**Comment by Jeavon** [comment]
Yup, I agree, I will split it out

**Comment by Jeavon** [comment]
Also, are you happy to stick with VS2015 or should I take it back?

**Comment by Jeavon** [comment]
Project split completed and merged

**Comment by JimBobSquarePants** [comment]
Awesome :smile: I'm all about 2015 now so we can keep it as that.

**Pull request merged**
