### PR TITLE
Migrating MSBuild-Integrated to Automatic Package Restore

### PR DESCRIPTION
**Pull request by Jeavon**
I don't believe we need .nuget folders as the solution is now VS2015/MSBuild v14 as per https://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore

Also upgrading NuGet.exe to v3.2

But some others may disagree....

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
You definitely don't need the .nuget folders. That's a hangover from a lack of knowledge on my part.
There's a good article on the correct approach here and some scripts in the comments that help clean up after you've used the old approach.

http://blog.davidebbo.com/2014/01/the-right-way-to-restore-nuget-packages.html

Looks like you've managed to clean it all out nicely.

**Comment by Jeavon** [comment]
Fab, glad we agree :)

**Comment by Jeavon** [comment]
@JimBobSquarePants now we're all on VS2015, I've added StyleCop.Analyzers (they support C# v6) to the new installer project, are you happy for me to add to the main project also?

**Comment by JimBobSquarePants** [comment]
Yeah. Big fan of the analysers project. Been using it for ImageProcessor.

**Comment by Jeavon** [comment]
Cool, I like them too although I haven't figured out how to stop them warring with ReSharper yet

**Pull request merged**
