### PR TITLE
Removed code from Installer as CDN is not required

### PR DESCRIPTION
**Pull request by KennethJakobsen**

### CODE REVIEW

**Comment by Jeavon** [comment]
@KennethJakobsen could you create fresh PR of everything against the current develop branch as this is quite confused now?

**Comment by KennethJakobsen** [comment]
@Jeavon I would love to, but I don't know how, still quite new to git

**Comment by Jeavon** [comment]
If you merge the current develop branch into your local CDN branch and then push to GitHub, it should update this PR with all changes

**Comment by KennethJakobsen** [comment]
When I try to merge, it  tells that the branch is already up to date

**Comment by KennethJakobsen** [comment]
Figured it out should now be able to merge

**Comment by JimBobSquarePants** [comment]
Hi @KennethJakobsen my apologies for the slow reply on this. It looks like something has not gone quite right as the are 47 file changes. My advise would be to use [GitHub for Desktop](https://desktop.github.com/) to do your merges. That way you can easily update from the develop branch and make only minimal changes.

**Pull request closed without merging**
